In [1]:
from sklearn import datasets

In [2]:
iris_dataset=datasets.load_iris()

In [3]:
print(iris_dataset.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Checking records of Target set

In [4]:
print(iris_dataset.target_names)

['setosa' 'versicolor' 'virginica']


In [5]:
type(iris_dataset.target)

numpy.ndarray

Checking top 5 records of dataset

In [6]:
print(iris_dataset.data[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [7]:
type(iris_dataset)

sklearn.utils.Bunch

In [8]:
print(iris_dataset.target[0:5])

[0 0 0 0 0]


Checking shape of dataset using shape functions

In [9]:
print(iris_dataset.data.shape)

(150, 4)


Splitting data using split function

In [10]:
from sklearn.model_selection import train_test_split

splitting dataset into training set and testing set

In [11]:
x_train,x_test,y_train,y_test = train_test_split(iris_dataset.data,iris_dataset.target,test_size=0.3)

Creating knn classifier

In [12]:
from sklearn.neighbors import KNeighborsClassifier

Generating model for k=2

In [13]:
knn2=KNeighborsClassifier(n_neighbors=2)

training the model using training sets

In [14]:
knn2.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=2)

predicting the response for the test dataset

In [15]:
y_pred2=knn2.predict(x_test)

In [17]:
from sklearn import metrics

In [18]:
print("Accuracy:",metrics.accuracy_score(y_test,y_pred2))

Accuracy: 0.9555555555555556


generating model for k=5

In [19]:
knn5=KNeighborsClassifier(n_neighbors=5)

In [20]:
knn5.fit(x_train,y_train)

KNeighborsClassifier()

predicting the response for the test dataset

In [21]:
y_pred5=knn5.predict(x_test)

In [22]:
print("Accuracy:",metrics.accuracy_score(y_test,y_pred5))

Accuracy: 0.9555555555555556
